#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="batch")]
public partial class bcDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void Insertbatch_confirmation(batch_confirmation instance);
  partial void Updatebatch_confirmation(batch_confirmation instance);
  partial void Deletebatch_confirmation(batch_confirmation instance);
  partial void Insertbatch_confirmation_action(batch_confirmation_action instance);
  partial void Updatebatch_confirmation_action(batch_confirmation_action instance);
  partial void Deletebatch_confirmation_action(batch_confirmation_action instance);
  #endregion
	
	public bcDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["batchConnectionString2"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public bcDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public bcDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public bcDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public bcDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<batch_confirmation> batch_confirmation
	{
		get
		{
			return this.GetTable<batch_confirmation>();
		}
	}
	
	public System.Data.Linq.Table<batch_confirmation_action> batch_confirmation_action
	{
		get
		{
			return this.GetTable<batch_confirmation_action>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.batch_confirmation")]
public partial class batch_confirmation : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _batch_no;
	
	private string _item_code;
	
	private System.Nullable<decimal> _qty;
	
	private string _Uom;
	
	private System.Nullable<System.DateTime> _shipping_date;
	
	private System.Nullable<int> _recipe_ver;
	
	private System.Nullable<int> _history;
	
	private string _planner_comment;
	
	private string _assign_lab;
	
	private string _adj_lab;
	
	private string _lab_comment;
	
	private int _r_status;
	
	private System.Nullable<System.DateTime> _add_date;
	
	private string _add_by;
	
	private System.Nullable<System.DateTime> _modify_date;
	
	private string _modify_by;
	
	private int _print_time;
	
	private string _take_by;
	
	private int _r_id;
	
	private string _r_orgn;
	
	private System.Nullable<int> _mail_times;
	
	private string _special_comment_1;
	
	private string _special_comment_2;
	
	private EntitySet<batch_confirmation_action> _batch_confirmation_action;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbatch_noChanging(string value);
    partial void Onbatch_noChanged();
    partial void Onitem_codeChanging(string value);
    partial void Onitem_codeChanged();
    partial void OnqtyChanging(System.Nullable<decimal> value);
    partial void OnqtyChanged();
    partial void OnUomChanging(string value);
    partial void OnUomChanged();
    partial void Onshipping_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onshipping_dateChanged();
    partial void Onrecipe_verChanging(System.Nullable<int> value);
    partial void Onrecipe_verChanged();
    partial void OnhistoryChanging(System.Nullable<int> value);
    partial void OnhistoryChanged();
    partial void Onplanner_commentChanging(string value);
    partial void Onplanner_commentChanged();
    partial void Onassign_labChanging(string value);
    partial void Onassign_labChanged();
    partial void Onadj_labChanging(string value);
    partial void Onadj_labChanged();
    partial void Onlab_commentChanging(string value);
    partial void Onlab_commentChanged();
    partial void Onr_statusChanging(int value);
    partial void Onr_statusChanged();
    partial void Onadd_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onadd_dateChanged();
    partial void Onadd_byChanging(string value);
    partial void Onadd_byChanged();
    partial void Onmodify_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onmodify_dateChanged();
    partial void Onmodify_byChanging(string value);
    partial void Onmodify_byChanged();
    partial void Oncheck_timesChanging(int value);
    partial void Oncheck_timesChanged();
    partial void Oncurrent_officerChanging(string value);
    partial void Oncurrent_officerChanged();
    partial void Onr_idChanging(int value);
    partial void Onr_idChanged();
    partial void Onr_orgnChanging(string value);
    partial void Onr_orgnChanged();
    partial void Onmail_timesChanging(System.Nullable<int> value);
    partial void Onmail_timesChanged();
    partial void Onspecial_comment_1Changing(string value);
    partial void Onspecial_comment_1Changed();
    partial void Onspecial_comment_2Changing(string value);
    partial void Onspecial_comment_2Changed();
    #endregion
	
	public batch_confirmation()
	{
		this._batch_confirmation_action = new EntitySet<batch_confirmation_action>(new Action<batch_confirmation_action>(this.attach_batch_confirmation_action), new Action<batch_confirmation_action>(this.detach_batch_confirmation_action));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_batch_no", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string batch_no
	{
		get
		{
			return this._batch_no;
		}
		set
		{
			if ((this._batch_no != value))
			{
				this.Onbatch_noChanging(value);
				this.SendPropertyChanging();
				this._batch_no = value;
				this.SendPropertyChanged("batch_no");
				this.Onbatch_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_code", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string item_code
	{
		get
		{
			return this._item_code;
		}
		set
		{
			if ((this._item_code != value))
			{
				this.Onitem_codeChanging(value);
				this.SendPropertyChanging();
				this._item_code = value;
				this.SendPropertyChanged("item_code");
				this.Onitem_codeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qty", DbType="Decimal(18,4)")]
	public System.Nullable<decimal> qty
	{
		get
		{
			return this._qty;
		}
		set
		{
			if ((this._qty != value))
			{
				this.OnqtyChanging(value);
				this.SendPropertyChanging();
				this._qty = value;
				this.SendPropertyChanged("qty");
				this.OnqtyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uom", DbType="VarChar(50)")]
	public string Uom
	{
		get
		{
			return this._Uom;
		}
		set
		{
			if ((this._Uom != value))
			{
				this.OnUomChanging(value);
				this.SendPropertyChanging();
				this._Uom = value;
				this.SendPropertyChanged("Uom");
				this.OnUomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shipping_date", DbType="Date")]
	public System.Nullable<System.DateTime> shipping_date
	{
		get
		{
			return this._shipping_date;
		}
		set
		{
			if ((this._shipping_date != value))
			{
				this.Onshipping_dateChanging(value);
				this.SendPropertyChanging();
				this._shipping_date = value;
				this.SendPropertyChanged("shipping_date");
				this.Onshipping_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recipe_ver", DbType="Int")]
	public System.Nullable<int> recipe_ver
	{
		get
		{
			return this._recipe_ver;
		}
		set
		{
			if ((this._recipe_ver != value))
			{
				this.Onrecipe_verChanging(value);
				this.SendPropertyChanging();
				this._recipe_ver = value;
				this.SendPropertyChanged("recipe_ver");
				this.Onrecipe_verChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_history", DbType="Int")]
	public System.Nullable<int> history
	{
		get
		{
			return this._history;
		}
		set
		{
			if ((this._history != value))
			{
				this.OnhistoryChanging(value);
				this.SendPropertyChanging();
				this._history = value;
				this.SendPropertyChanged("history");
				this.OnhistoryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planner_comment", DbType="NVarChar(MAX)")]
	public string planner_comment
	{
		get
		{
			return this._planner_comment;
		}
		set
		{
			if ((this._planner_comment != value))
			{
				this.Onplanner_commentChanging(value);
				this.SendPropertyChanging();
				this._planner_comment = value;
				this.SendPropertyChanged("planner_comment");
				this.Onplanner_commentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assign_lab", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string assign_lab
	{
		get
		{
			return this._assign_lab;
		}
		set
		{
			if ((this._assign_lab != value))
			{
				this.Onassign_labChanging(value);
				this.SendPropertyChanging();
				this._assign_lab = value;
				this.SendPropertyChanged("assign_lab");
				this.Onassign_labChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adj_lab", DbType="NVarChar(50)")]
	public string adj_lab
	{
		get
		{
			return this._adj_lab;
		}
		set
		{
			if ((this._adj_lab != value))
			{
				this.Onadj_labChanging(value);
				this.SendPropertyChanging();
				this._adj_lab = value;
				this.SendPropertyChanged("adj_lab");
				this.Onadj_labChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lab_comment", DbType="NVarChar(MAX)")]
	public string lab_comment
	{
		get
		{
			return this._lab_comment;
		}
		set
		{
			if ((this._lab_comment != value))
			{
				this.Onlab_commentChanging(value);
				this.SendPropertyChanging();
				this._lab_comment = value;
				this.SendPropertyChanged("lab_comment");
				this.Onlab_commentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r_status", DbType="Int NOT NULL")]
	public int r_status
	{
		get
		{
			return this._r_status;
		}
		set
		{
			if ((this._r_status != value))
			{
				this.Onr_statusChanging(value);
				this.SendPropertyChanging();
				this._r_status = value;
				this.SendPropertyChanged("r_status");
				this.Onr_statusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_add_date", DbType="DateTime")]
	public System.Nullable<System.DateTime> add_date
	{
		get
		{
			return this._add_date;
		}
		set
		{
			if ((this._add_date != value))
			{
				this.Onadd_dateChanging(value);
				this.SendPropertyChanging();
				this._add_date = value;
				this.SendPropertyChanged("add_date");
				this.Onadd_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_add_by", DbType="VarChar(50)")]
	public string add_by
	{
		get
		{
			return this._add_by;
		}
		set
		{
			if ((this._add_by != value))
			{
				this.Onadd_byChanging(value);
				this.SendPropertyChanging();
				this._add_by = value;
				this.SendPropertyChanged("add_by");
				this.Onadd_byChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modify_date", DbType="DateTime")]
	public System.Nullable<System.DateTime> modify_date
	{
		get
		{
			return this._modify_date;
		}
		set
		{
			if ((this._modify_date != value))
			{
				this.Onmodify_dateChanging(value);
				this.SendPropertyChanging();
				this._modify_date = value;
				this.SendPropertyChanged("modify_date");
				this.Onmodify_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modify_by", DbType="VarChar(50)")]
	public string modify_by
	{
		get
		{
			return this._modify_by;
		}
		set
		{
			if ((this._modify_by != value))
			{
				this.Onmodify_byChanging(value);
				this.SendPropertyChanging();
				this._modify_by = value;
				this.SendPropertyChanged("modify_by");
				this.Onmodify_byChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_print_time", DbType="Int NOT NULL")]
	public int check_times
	{
		get
		{
			return this._print_time;
		}
		set
		{
			if ((this._print_time != value))
			{
				this.Oncheck_timesChanging(value);
				this.SendPropertyChanging();
				this._print_time = value;
				this.SendPropertyChanged("check_times");
				this.Oncheck_timesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_take_by", DbType="VarChar(50)")]
	public string current_officer
	{
		get
		{
			return this._take_by;
		}
		set
		{
			if ((this._take_by != value))
			{
				this.Oncurrent_officerChanging(value);
				this.SendPropertyChanging();
				this._take_by = value;
				this.SendPropertyChanged("current_officer");
				this.Oncurrent_officerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int r_id
	{
		get
		{
			return this._r_id;
		}
		set
		{
			if ((this._r_id != value))
			{
				this.Onr_idChanging(value);
				this.SendPropertyChanging();
				this._r_id = value;
				this.SendPropertyChanged("r_id");
				this.Onr_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r_orgn", DbType="NVarChar(50)")]
	public string r_orgn
	{
		get
		{
			return this._r_orgn;
		}
		set
		{
			if ((this._r_orgn != value))
			{
				this.Onr_orgnChanging(value);
				this.SendPropertyChanging();
				this._r_orgn = value;
				this.SendPropertyChanged("r_orgn");
				this.Onr_orgnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail_times", DbType="Int")]
	public System.Nullable<int> mail_times
	{
		get
		{
			return this._mail_times;
		}
		set
		{
			if ((this._mail_times != value))
			{
				this.Onmail_timesChanging(value);
				this.SendPropertyChanging();
				this._mail_times = value;
				this.SendPropertyChanged("mail_times");
				this.Onmail_timesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_special_comment_1", DbType="NVarChar(MAX)")]
	public string special_comment_1
	{
		get
		{
			return this._special_comment_1;
		}
		set
		{
			if ((this._special_comment_1 != value))
			{
				this.Onspecial_comment_1Changing(value);
				this.SendPropertyChanging();
				this._special_comment_1 = value;
				this.SendPropertyChanged("special_comment_1");
				this.Onspecial_comment_1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_special_comment_2", DbType="NVarChar(MAX)")]
	public string special_comment_2
	{
		get
		{
			return this._special_comment_2;
		}
		set
		{
			if ((this._special_comment_2 != value))
			{
				this.Onspecial_comment_2Changing(value);
				this.SendPropertyChanging();
				this._special_comment_2 = value;
				this.SendPropertyChanged("special_comment_2");
				this.Onspecial_comment_2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="batch_confirmation_batch_confirmation_action", Storage="_batch_confirmation_action", ThisKey="r_id", OtherKey="r_id")]
	public EntitySet<batch_confirmation_action> batch_confirmation_action
	{
		get
		{
			return this._batch_confirmation_action;
		}
		set
		{
			this._batch_confirmation_action.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_batch_confirmation_action(batch_confirmation_action entity)
	{
		this.SendPropertyChanging();
		entity.batch_confirmation = this;
	}
	
	private void detach_batch_confirmation_action(batch_confirmation_action entity)
	{
		this.SendPropertyChanging();
		entity.batch_confirmation = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.batch_confirmation_action")]
public partial class batch_confirmation_action : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _a_id;
	
	private string _batch_no;
	
	private string _action;
	
	private string _comment;
	
	private string _operator;
	
	private System.Nullable<System.DateTime> _login_time;
	
	private int _r_id;
	
	private EntityRef<batch_confirmation> _batch_confirmation;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ona_idChanging(int value);
    partial void Ona_idChanged();
    partial void Onbatch_noChanging(string value);
    partial void Onbatch_noChanged();
    partial void OnactionChanging(string value);
    partial void OnactionChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    partial void OnoperatorChanging(string value);
    partial void OnoperatorChanged();
    partial void Onlogin_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onlogin_timeChanged();
    partial void Onr_idChanging(int value);
    partial void Onr_idChanged();
    #endregion
	
	public batch_confirmation_action()
	{
		this._batch_confirmation = default(EntityRef<batch_confirmation>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int a_id
	{
		get
		{
			return this._a_id;
		}
		set
		{
			if ((this._a_id != value))
			{
				this.Ona_idChanging(value);
				this.SendPropertyChanging();
				this._a_id = value;
				this.SendPropertyChanged("a_id");
				this.Ona_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_batch_no", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string batch_no
	{
		get
		{
			return this._batch_no;
		}
		set
		{
			if ((this._batch_no != value))
			{
				this.Onbatch_noChanging(value);
				this.SendPropertyChanging();
				this._batch_no = value;
				this.SendPropertyChanged("batch_no");
				this.Onbatch_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_action", DbType="NVarChar(50)")]
	public string action
	{
		get
		{
			return this._action;
		}
		set
		{
			if ((this._action != value))
			{
				this.OnactionChanging(value);
				this.SendPropertyChanging();
				this._action = value;
				this.SendPropertyChanged("action");
				this.OnactionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="NVarChar(MAX)")]
	public string comment
	{
		get
		{
			return this._comment;
		}
		set
		{
			if ((this._comment != value))
			{
				this.OncommentChanging(value);
				this.SendPropertyChanging();
				this._comment = value;
				this.SendPropertyChanged("comment");
				this.OncommentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="operator", Storage="_operator", DbType="VarChar(50)")]
	public string @operator
	{
		get
		{
			return this._operator;
		}
		set
		{
			if ((this._operator != value))
			{
				this.OnoperatorChanging(value);
				this.SendPropertyChanging();
				this._operator = value;
				this.SendPropertyChanged("@operator");
				this.OnoperatorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login_time", DbType="DateTime")]
	public System.Nullable<System.DateTime> login_time
	{
		get
		{
			return this._login_time;
		}
		set
		{
			if ((this._login_time != value))
			{
				this.Onlogin_timeChanging(value);
				this.SendPropertyChanging();
				this._login_time = value;
				this.SendPropertyChanged("login_time");
				this.Onlogin_timeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r_id", DbType="Int NOT NULL")]
	public int r_id
	{
		get
		{
			return this._r_id;
		}
		set
		{
			if ((this._r_id != value))
			{
				if (this._batch_confirmation.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onr_idChanging(value);
				this.SendPropertyChanging();
				this._r_id = value;
				this.SendPropertyChanged("r_id");
				this.Onr_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="batch_confirmation_batch_confirmation_action", Storage="_batch_confirmation", ThisKey="r_id", OtherKey="r_id", IsForeignKey=true)]
	public batch_confirmation batch_confirmation
	{
		get
		{
			return this._batch_confirmation.Entity;
		}
		set
		{
			batch_confirmation previousValue = this._batch_confirmation.Entity;
			if (((previousValue != value) 
						|| (this._batch_confirmation.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._batch_confirmation.Entity = null;
					previousValue.batch_confirmation_action.Remove(this);
				}
				this._batch_confirmation.Entity = value;
				if ((value != null))
				{
					value.batch_confirmation_action.Add(this);
					this._r_id = value.r_id;
				}
				else
				{
					this._r_id = default(int);
				}
				this.SendPropertyChanged("batch_confirmation");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
