#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="batch")]
public partial class BVReportDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void Insertbv_report_data_history(bv_report_data_history instance);
  partial void Updatebv_report_data_history(bv_report_data_history instance);
  partial void Deletebv_report_data_history(bv_report_data_history instance);
  partial void InsertBVReportDataWithWeek(BVReportDataWithWeek instance);
  partial void UpdateBVReportDataWithWeek(BVReportDataWithWeek instance);
  partial void DeleteBVReportDataWithWeek(BVReportDataWithWeek instance);
  #endregion
	
	public BVReportDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["batchConnectionString3"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public BVReportDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BVReportDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BVReportDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BVReportDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<bv_report_data_history> bv_report_data_histories
	{
		get
		{
			return this.GetTable<bv_report_data_history>();
		}
	}
	
	public System.Data.Linq.Table<cell_info> cell_infos
	{
		get
		{
			return this.GetTable<cell_info>();
		}
	}
	
	public System.Data.Linq.Table<BVReportDataWithWeek> BVReportDataWithWeeks
	{
		get
		{
			return this.GetTable<BVReportDataWithWeek>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bv_report_data_his")]
public partial class bv_report_data_history : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _LINE_KEY;
	
	private string _BATCH_NO;
	
	private string _CELL;
	
	private string _ITEM_CODE;
	
	private string _STEP;
	
	private string _STATUS;
	
	private string _OPRN_NO;
	
	private System.Nullable<int> _LINE_NO;
	
	private string _ITEM_NO;
	
	private string _UM;
	
	private string _LOT_NO;
	
	private System.Nullable<System.DateTime> _ACTUAL_CMPLT_DATE;
	
	private System.Nullable<decimal> _WIP_QTY;
	
	private System.Nullable<decimal> _ADD_QTY;
	
	private string _CONTAINER;
	
	private string _ADDED_BY;
	
	private System.Nullable<System.DateTime> _DATE_ADDED;
	
	private System.Nullable<decimal> _DIFF_MINS;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLINE_KEYChanging(string value);
    partial void OnLINE_KEYChanged();
    partial void OnBATCH_NOChanging(string value);
    partial void OnBATCH_NOChanged();
    partial void OnCELLChanging(string value);
    partial void OnCELLChanged();
    partial void OnITEM_CODEChanging(string value);
    partial void OnITEM_CODEChanged();
    partial void OnSTEPChanging(string value);
    partial void OnSTEPChanged();
    partial void OnSTATUSChanging(string value);
    partial void OnSTATUSChanged();
    partial void OnOPRN_NOChanging(string value);
    partial void OnOPRN_NOChanged();
    partial void OnLINE_NOChanging(System.Nullable<int> value);
    partial void OnLINE_NOChanged();
    partial void OnITEM_NOChanging(string value);
    partial void OnITEM_NOChanged();
    partial void OnUMChanging(string value);
    partial void OnUMChanged();
    partial void OnLOT_NOChanging(string value);
    partial void OnLOT_NOChanged();
    partial void OnACTUAL_CMPLT_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnACTUAL_CMPLT_DATEChanged();
    partial void OnWIP_QTYChanging(System.Nullable<decimal> value);
    partial void OnWIP_QTYChanged();
    partial void OnADD_QTYChanging(System.Nullable<decimal> value);
    partial void OnADD_QTYChanged();
    partial void OnCONTAINERChanging(string value);
    partial void OnCONTAINERChanged();
    partial void OnADDED_BYChanging(string value);
    partial void OnADDED_BYChanged();
    partial void OnDATE_ADDEDChanging(System.Nullable<System.DateTime> value);
    partial void OnDATE_ADDEDChanged();
    partial void OnDIFF_MINSChanging(System.Nullable<decimal> value);
    partial void OnDIFF_MINSChanged();
    #endregion
	
	public bv_report_data_history()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINE_KEY", DbType="NVarChar(80) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string LINE_KEY
	{
		get
		{
			return this._LINE_KEY;
		}
		set
		{
			if ((this._LINE_KEY != value))
			{
				this.OnLINE_KEYChanging(value);
				this.SendPropertyChanging();
				this._LINE_KEY = value;
				this.SendPropertyChanged("LINE_KEY");
				this.OnLINE_KEYChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BATCH_NO", DbType="NVarChar(32) NOT NULL", CanBeNull=false)]
	public string BATCH_NO
	{
		get
		{
			return this._BATCH_NO;
		}
		set
		{
			if ((this._BATCH_NO != value))
			{
				this.OnBATCH_NOChanging(value);
				this.SendPropertyChanging();
				this._BATCH_NO = value;
				this.SendPropertyChanged("BATCH_NO");
				this.OnBATCH_NOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CELL", DbType="NVarChar(100)")]
	public string CELL
	{
		get
		{
			return this._CELL;
		}
		set
		{
			if ((this._CELL != value))
			{
				this.OnCELLChanging(value);
				this.SendPropertyChanging();
				this._CELL = value;
				this.SendPropertyChanged("CELL");
				this.OnCELLChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEM_CODE", DbType="NVarChar(40)")]
	public string ITEM_CODE
	{
		get
		{
			return this._ITEM_CODE;
		}
		set
		{
			if ((this._ITEM_CODE != value))
			{
				this.OnITEM_CODEChanging(value);
				this.SendPropertyChanging();
				this._ITEM_CODE = value;
				this.SendPropertyChanged("ITEM_CODE");
				this.OnITEM_CODEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STEP", DbType="VarChar(50)")]
	public string STEP
	{
		get
		{
			return this._STEP;
		}
		set
		{
			if ((this._STEP != value))
			{
				this.OnSTEPChanging(value);
				this.SendPropertyChanging();
				this._STEP = value;
				this.SendPropertyChanged("STEP");
				this.OnSTEPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="NVarChar(32)")]
	public string STATUS
	{
		get
		{
			return this._STATUS;
		}
		set
		{
			if ((this._STATUS != value))
			{
				this.OnSTATUSChanging(value);
				this.SendPropertyChanging();
				this._STATUS = value;
				this.SendPropertyChanged("STATUS");
				this.OnSTATUSChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPRN_NO", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
	public string OPRN_NO
	{
		get
		{
			return this._OPRN_NO;
		}
		set
		{
			if ((this._OPRN_NO != value))
			{
				this.OnOPRN_NOChanging(value);
				this.SendPropertyChanging();
				this._OPRN_NO = value;
				this.SendPropertyChanged("OPRN_NO");
				this.OnOPRN_NOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINE_NO", DbType="Int")]
	public System.Nullable<int> LINE_NO
	{
		get
		{
			return this._LINE_NO;
		}
		set
		{
			if ((this._LINE_NO != value))
			{
				this.OnLINE_NOChanging(value);
				this.SendPropertyChanging();
				this._LINE_NO = value;
				this.SendPropertyChanged("LINE_NO");
				this.OnLINE_NOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEM_NO", DbType="NVarChar(32)")]
	public string ITEM_NO
	{
		get
		{
			return this._ITEM_NO;
		}
		set
		{
			if ((this._ITEM_NO != value))
			{
				this.OnITEM_NOChanging(value);
				this.SendPropertyChanging();
				this._ITEM_NO = value;
				this.SendPropertyChanged("ITEM_NO");
				this.OnITEM_NOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UM", DbType="NVarChar(4)")]
	public string UM
	{
		get
		{
			return this._UM;
		}
		set
		{
			if ((this._UM != value))
			{
				this.OnUMChanging(value);
				this.SendPropertyChanging();
				this._UM = value;
				this.SendPropertyChanged("UM");
				this.OnUMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOT_NO", DbType="NVarChar(32)")]
	public string LOT_NO
	{
		get
		{
			return this._LOT_NO;
		}
		set
		{
			if ((this._LOT_NO != value))
			{
				this.OnLOT_NOChanging(value);
				this.SendPropertyChanging();
				this._LOT_NO = value;
				this.SendPropertyChanged("LOT_NO");
				this.OnLOT_NOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTUAL_CMPLT_DATE", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> ACTUAL_CMPLT_DATE
	{
		get
		{
			return this._ACTUAL_CMPLT_DATE;
		}
		set
		{
			if ((this._ACTUAL_CMPLT_DATE != value))
			{
				this.OnACTUAL_CMPLT_DATEChanging(value);
				this.SendPropertyChanging();
				this._ACTUAL_CMPLT_DATE = value;
				this.SendPropertyChanged("ACTUAL_CMPLT_DATE");
				this.OnACTUAL_CMPLT_DATEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WIP_QTY", DbType="Decimal(30,10)")]
	public System.Nullable<decimal> WIP_QTY
	{
		get
		{
			return this._WIP_QTY;
		}
		set
		{
			if ((this._WIP_QTY != value))
			{
				this.OnWIP_QTYChanging(value);
				this.SendPropertyChanging();
				this._WIP_QTY = value;
				this.SendPropertyChanged("WIP_QTY");
				this.OnWIP_QTYChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADD_QTY", DbType="Decimal(30,10)")]
	public System.Nullable<decimal> ADD_QTY
	{
		get
		{
			return this._ADD_QTY;
		}
		set
		{
			if ((this._ADD_QTY != value))
			{
				this.OnADD_QTYChanging(value);
				this.SendPropertyChanging();
				this._ADD_QTY = value;
				this.SendPropertyChanged("ADD_QTY");
				this.OnADD_QTYChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTAINER", DbType="NVarChar(32)")]
	public string CONTAINER
	{
		get
		{
			return this._CONTAINER;
		}
		set
		{
			if ((this._CONTAINER != value))
			{
				this.OnCONTAINERChanging(value);
				this.SendPropertyChanging();
				this._CONTAINER = value;
				this.SendPropertyChanged("CONTAINER");
				this.OnCONTAINERChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDED_BY", DbType="NVarChar(240)")]
	public string ADDED_BY
	{
		get
		{
			return this._ADDED_BY;
		}
		set
		{
			if ((this._ADDED_BY != value))
			{
				this.OnADDED_BYChanging(value);
				this.SendPropertyChanging();
				this._ADDED_BY = value;
				this.SendPropertyChanged("ADDED_BY");
				this.OnADDED_BYChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_ADDED", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> DATE_ADDED
	{
		get
		{
			return this._DATE_ADDED;
		}
		set
		{
			if ((this._DATE_ADDED != value))
			{
				this.OnDATE_ADDEDChanging(value);
				this.SendPropertyChanging();
				this._DATE_ADDED = value;
				this.SendPropertyChanged("DATE_ADDED");
				this.OnDATE_ADDEDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIFF_MINS", DbType="Decimal(18,8)")]
	public System.Nullable<decimal> DIFF_MINS
	{
		get
		{
			return this._DIFF_MINS;
		}
		set
		{
			if ((this._DIFF_MINS != value))
			{
				this.OnDIFF_MINSChanging(value);
				this.SendPropertyChanging();
				this._DIFF_MINS = value;
				this.SendPropertyChanged("DIFF_MINS");
				this.OnDIFF_MINSChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cell_info")]
public partial class cell_info
{
	
	private int _cell_id;
	
	private string _cell_name;
	
	private string _cell_supervisor;
	
	private string _cell_BU;
	
	private System.Nullable<int> _cell_WIP_limit;
	
	private System.Nullable<int> _cell_WIP_tolerance;
	
	private System.Nullable<double> _cell_CT;
	
	private string _report_building;
	
	private string _plant_code;
	
	public cell_info()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int cell_id
	{
		get
		{
			return this._cell_id;
		}
		set
		{
			if ((this._cell_id != value))
			{
				this._cell_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell_name", DbType="VarChar(50)")]
	public string cell_name
	{
		get
		{
			return this._cell_name;
		}
		set
		{
			if ((this._cell_name != value))
			{
				this._cell_name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell_supervisor", DbType="VarChar(50)")]
	public string cell_supervisor
	{
		get
		{
			return this._cell_supervisor;
		}
		set
		{
			if ((this._cell_supervisor != value))
			{
				this._cell_supervisor = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell_BU", DbType="VarChar(50)")]
	public string cell_BU
	{
		get
		{
			return this._cell_BU;
		}
		set
		{
			if ((this._cell_BU != value))
			{
				this._cell_BU = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell_WIP_limit", DbType="Int")]
	public System.Nullable<int> cell_WIP_limit
	{
		get
		{
			return this._cell_WIP_limit;
		}
		set
		{
			if ((this._cell_WIP_limit != value))
			{
				this._cell_WIP_limit = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell_WIP_tolerance", DbType="Int")]
	public System.Nullable<int> cell_WIP_tolerance
	{
		get
		{
			return this._cell_WIP_tolerance;
		}
		set
		{
			if ((this._cell_WIP_tolerance != value))
			{
				this._cell_WIP_tolerance = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell_CT", DbType="Float")]
	public System.Nullable<double> cell_CT
	{
		get
		{
			return this._cell_CT;
		}
		set
		{
			if ((this._cell_CT != value))
			{
				this._cell_CT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_report_building", DbType="VarChar(50)")]
	public string report_building
	{
		get
		{
			return this._report_building;
		}
		set
		{
			if ((this._report_building != value))
			{
				this._report_building = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plant_code", DbType="VarChar(50)")]
	public string plant_code
	{
		get
		{
			return this._plant_code;
		}
		set
		{
			if ((this._plant_code != value))
			{
				this._plant_code = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BVReportDataWithWeek")]
public partial class BVReportDataWithWeek : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _weekdate;
	
	private string _LINE_KEY;
	
	private string _BATCH_NO;
	
	private string _CELL;
	
	private string _ITEM_CODE;
	
	private string _STEP;
	
	private string _STATUS;
	
	private string _OPRN_NO;
	
	private System.Nullable<int> _LINE_NO;
	
	private string _ITEM_NO;
	
	private string _UM;
	
	private string _LOT_NO;
	
	private System.Nullable<System.DateTime> _ACTUAL_CMPLT_DATE;
	
	private System.Nullable<decimal> _WIP_QTY;
	
	private System.Nullable<decimal> _ADD_QTY;
	
	private string _CONTAINER;
	
	private string _ADDED_BY;
	
	private System.Nullable<System.DateTime> _DATE_ADDED;
	
	private System.Nullable<decimal> _DIFF_MINS;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnweekdateChanging(string value);
    partial void OnweekdateChanged();
    partial void OnLINE_KEYChanging(string value);
    partial void OnLINE_KEYChanged();
    partial void OnBATCH_NOChanging(string value);
    partial void OnBATCH_NOChanged();
    partial void OnCELLChanging(string value);
    partial void OnCELLChanged();
    partial void OnITEM_CODEChanging(string value);
    partial void OnITEM_CODEChanged();
    partial void OnSTEPChanging(string value);
    partial void OnSTEPChanged();
    partial void OnSTATUSChanging(string value);
    partial void OnSTATUSChanged();
    partial void OnOPRN_NOChanging(string value);
    partial void OnOPRN_NOChanged();
    partial void OnLINE_NOChanging(System.Nullable<int> value);
    partial void OnLINE_NOChanged();
    partial void OnITEM_NOChanging(string value);
    partial void OnITEM_NOChanged();
    partial void OnUMChanging(string value);
    partial void OnUMChanged();
    partial void OnLOT_NOChanging(string value);
    partial void OnLOT_NOChanged();
    partial void OnACTUAL_CMPLT_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnACTUAL_CMPLT_DATEChanged();
    partial void OnWIP_QTYChanging(System.Nullable<decimal> value);
    partial void OnWIP_QTYChanged();
    partial void OnADD_QTYChanging(System.Nullable<decimal> value);
    partial void OnADD_QTYChanged();
    partial void OnCONTAINERChanging(string value);
    partial void OnCONTAINERChanged();
    partial void OnADDED_BYChanging(string value);
    partial void OnADDED_BYChanged();
    partial void OnDATE_ADDEDChanging(System.Nullable<System.DateTime> value);
    partial void OnDATE_ADDEDChanged();
    partial void OnDIFF_MINSChanging(System.Nullable<decimal> value);
    partial void OnDIFF_MINSChanged();
    #endregion
	
	public BVReportDataWithWeek()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weekdate", DbType="VarChar(30)")]
	public string weekdate
	{
		get
		{
			return this._weekdate;
		}
		set
		{
			if ((this._weekdate != value))
			{
				this.OnweekdateChanging(value);
				this.SendPropertyChanging();
				this._weekdate = value;
				this.SendPropertyChanged("weekdate");
				this.OnweekdateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINE_KEY", DbType="NVarChar(80) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string LINE_KEY
	{
		get
		{
			return this._LINE_KEY;
		}
		set
		{
			if ((this._LINE_KEY != value))
			{
				this.OnLINE_KEYChanging(value);
				this.SendPropertyChanging();
				this._LINE_KEY = value;
				this.SendPropertyChanged("LINE_KEY");
				this.OnLINE_KEYChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BATCH_NO", DbType="NVarChar(32) NOT NULL", CanBeNull=false)]
	public string BATCH_NO
	{
		get
		{
			return this._BATCH_NO;
		}
		set
		{
			if ((this._BATCH_NO != value))
			{
				this.OnBATCH_NOChanging(value);
				this.SendPropertyChanging();
				this._BATCH_NO = value;
				this.SendPropertyChanged("BATCH_NO");
				this.OnBATCH_NOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CELL", DbType="NVarChar(100)")]
	public string CELL
	{
		get
		{
			return this._CELL;
		}
		set
		{
			if ((this._CELL != value))
			{
				this.OnCELLChanging(value);
				this.SendPropertyChanging();
				this._CELL = value;
				this.SendPropertyChanged("CELL");
				this.OnCELLChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEM_CODE", DbType="NVarChar(40)")]
	public string ITEM_CODE
	{
		get
		{
			return this._ITEM_CODE;
		}
		set
		{
			if ((this._ITEM_CODE != value))
			{
				this.OnITEM_CODEChanging(value);
				this.SendPropertyChanging();
				this._ITEM_CODE = value;
				this.SendPropertyChanged("ITEM_CODE");
				this.OnITEM_CODEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STEP", DbType="VarChar(50)")]
	public string STEP
	{
		get
		{
			return this._STEP;
		}
		set
		{
			if ((this._STEP != value))
			{
				this.OnSTEPChanging(value);
				this.SendPropertyChanging();
				this._STEP = value;
				this.SendPropertyChanged("STEP");
				this.OnSTEPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="NVarChar(32)")]
	public string STATUS
	{
		get
		{
			return this._STATUS;
		}
		set
		{
			if ((this._STATUS != value))
			{
				this.OnSTATUSChanging(value);
				this.SendPropertyChanging();
				this._STATUS = value;
				this.SendPropertyChanged("STATUS");
				this.OnSTATUSChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPRN_NO", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
	public string OPRN_NO
	{
		get
		{
			return this._OPRN_NO;
		}
		set
		{
			if ((this._OPRN_NO != value))
			{
				this.OnOPRN_NOChanging(value);
				this.SendPropertyChanging();
				this._OPRN_NO = value;
				this.SendPropertyChanged("OPRN_NO");
				this.OnOPRN_NOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINE_NO", DbType="Int")]
	public System.Nullable<int> LINE_NO
	{
		get
		{
			return this._LINE_NO;
		}
		set
		{
			if ((this._LINE_NO != value))
			{
				this.OnLINE_NOChanging(value);
				this.SendPropertyChanging();
				this._LINE_NO = value;
				this.SendPropertyChanged("LINE_NO");
				this.OnLINE_NOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEM_NO", DbType="NVarChar(32)")]
	public string ITEM_NO
	{
		get
		{
			return this._ITEM_NO;
		}
		set
		{
			if ((this._ITEM_NO != value))
			{
				this.OnITEM_NOChanging(value);
				this.SendPropertyChanging();
				this._ITEM_NO = value;
				this.SendPropertyChanged("ITEM_NO");
				this.OnITEM_NOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UM", DbType="NVarChar(4)")]
	public string UM
	{
		get
		{
			return this._UM;
		}
		set
		{
			if ((this._UM != value))
			{
				this.OnUMChanging(value);
				this.SendPropertyChanging();
				this._UM = value;
				this.SendPropertyChanged("UM");
				this.OnUMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOT_NO", DbType="NVarChar(32)")]
	public string LOT_NO
	{
		get
		{
			return this._LOT_NO;
		}
		set
		{
			if ((this._LOT_NO != value))
			{
				this.OnLOT_NOChanging(value);
				this.SendPropertyChanging();
				this._LOT_NO = value;
				this.SendPropertyChanged("LOT_NO");
				this.OnLOT_NOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTUAL_CMPLT_DATE", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> ACTUAL_CMPLT_DATE
	{
		get
		{
			return this._ACTUAL_CMPLT_DATE;
		}
		set
		{
			if ((this._ACTUAL_CMPLT_DATE != value))
			{
				this.OnACTUAL_CMPLT_DATEChanging(value);
				this.SendPropertyChanging();
				this._ACTUAL_CMPLT_DATE = value;
				this.SendPropertyChanged("ACTUAL_CMPLT_DATE");
				this.OnACTUAL_CMPLT_DATEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WIP_QTY", DbType="Decimal(30,10)")]
	public System.Nullable<decimal> WIP_QTY
	{
		get
		{
			return this._WIP_QTY;
		}
		set
		{
			if ((this._WIP_QTY != value))
			{
				this.OnWIP_QTYChanging(value);
				this.SendPropertyChanging();
				this._WIP_QTY = value;
				this.SendPropertyChanged("WIP_QTY");
				this.OnWIP_QTYChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADD_QTY", DbType="Decimal(30,10)")]
	public System.Nullable<decimal> ADD_QTY
	{
		get
		{
			return this._ADD_QTY;
		}
		set
		{
			if ((this._ADD_QTY != value))
			{
				this.OnADD_QTYChanging(value);
				this.SendPropertyChanging();
				this._ADD_QTY = value;
				this.SendPropertyChanged("ADD_QTY");
				this.OnADD_QTYChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTAINER", DbType="NVarChar(32)")]
	public string CONTAINER
	{
		get
		{
			return this._CONTAINER;
		}
		set
		{
			if ((this._CONTAINER != value))
			{
				this.OnCONTAINERChanging(value);
				this.SendPropertyChanging();
				this._CONTAINER = value;
				this.SendPropertyChanged("CONTAINER");
				this.OnCONTAINERChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDED_BY", DbType="NVarChar(240)")]
	public string ADDED_BY
	{
		get
		{
			return this._ADDED_BY;
		}
		set
		{
			if ((this._ADDED_BY != value))
			{
				this.OnADDED_BYChanging(value);
				this.SendPropertyChanging();
				this._ADDED_BY = value;
				this.SendPropertyChanged("ADDED_BY");
				this.OnADDED_BYChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_ADDED", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> DATE_ADDED
	{
		get
		{
			return this._DATE_ADDED;
		}
		set
		{
			if ((this._DATE_ADDED != value))
			{
				this.OnDATE_ADDEDChanging(value);
				this.SendPropertyChanging();
				this._DATE_ADDED = value;
				this.SendPropertyChanged("DATE_ADDED");
				this.OnDATE_ADDEDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIFF_MINS", DbType="Decimal(18,8)")]
	public System.Nullable<decimal> DIFF_MINS
	{
		get
		{
			return this._DIFF_MINS;
		}
		set
		{
			if ((this._DIFF_MINS != value))
			{
				this.OnDIFF_MINSChanging(value);
				this.SendPropertyChanging();
				this._DIFF_MINS = value;
				this.SendPropertyChanged("DIFF_MINS");
				this.OnDIFF_MINSChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
