#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="batch")]
public partial class LabDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertLab(Lab instance);
  partial void UpdateLab(Lab instance);
  partial void DeleteLab(Lab instance);
  #endregion
	
	public LabDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["batchConnectionString2"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public LabDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LabDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LabDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LabDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Lab> Lab
	{
		get
		{
			return this.GetTable<Lab>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lab")]
public partial class Lab : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _lab_name;
	
	private string _adj_lab_list;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlab_nameChanging(string value);
    partial void Onlab_nameChanged();
    partial void Onadj_lab_listChanging(string value);
    partial void Onadj_lab_listChanged();
    #endregion
	
	public Lab()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lab_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string lab_name
	{
		get
		{
			return this._lab_name;
		}
		set
		{
			if ((this._lab_name != value))
			{
				this.Onlab_nameChanging(value);
				this.SendPropertyChanging();
				this._lab_name = value;
				this.SendPropertyChanged("lab_name");
				this.Onlab_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adj_lab_list", DbType="NVarChar(MAX)")]
	public string adj_lab_list
	{
		get
		{
			return this._adj_lab_list;
		}
		set
		{
			if ((this._adj_lab_list != value))
			{
				this.Onadj_lab_listChanging(value);
				this.SendPropertyChanging();
				this._adj_lab_list = value;
				this.SendPropertyChanged("adj_lab_list");
				this.Onadj_lab_listChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
