#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="batch")]
public partial class packageDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void Insertpackage_category(package_category instance);
  partial void Updatepackage_category(package_category instance);
  partial void Deletepackage_category(package_category instance);
  partial void Insertpackage_using(package_using instance);
  partial void Updatepackage_using(package_using instance);
  partial void Deletepackage_using(package_using instance);
  partial void Insertcell_info(cell_info instance);
  partial void Updatecell_info(cell_info instance);
  partial void Deletecell_info(cell_info instance);
  partial void Insertpackage_user(package_user instance);
  partial void Updatepackage_user(package_user instance);
  partial void Deletepackage_user(package_user instance);
  #endregion
	
	public packageDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["batchConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public packageDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public packageDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public packageDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public packageDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<package_category> package_category
	{
		get
		{
			return this.GetTable<package_category>();
		}
	}
	
	public System.Data.Linq.Table<package_using> package_using
	{
		get
		{
			return this.GetTable<package_using>();
		}
	}
	
	public System.Data.Linq.Table<cell_info> cell_info
	{
		get
		{
			return this.GetTable<cell_info>();
		}
	}
	
	public System.Data.Linq.Table<package_user> package_user
	{
		get
		{
			return this.GetTable<package_user>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.package_category")]
public partial class package_category : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _p_id;
	
	private string _p_name;
	
	private string _p_desc;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onp_idChanging(int value);
    partial void Onp_idChanged();
    partial void Onp_nameChanging(string value);
    partial void Onp_nameChanged();
    partial void Onp_descChanging(string value);
    partial void Onp_descChanged();
    #endregion
	
	public package_category()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int p_id
	{
		get
		{
			return this._p_id;
		}
		set
		{
			if ((this._p_id != value))
			{
				this.Onp_idChanging(value);
				this.SendPropertyChanging();
				this._p_id = value;
				this.SendPropertyChanged("p_id");
				this.Onp_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_name", DbType="NVarChar(50)")]
	public string p_name
	{
		get
		{
			return this._p_name;
		}
		set
		{
			if ((this._p_name != value))
			{
				this.Onp_nameChanging(value);
				this.SendPropertyChanging();
				this._p_name = value;
				this.SendPropertyChanged("p_name");
				this.Onp_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_desc", DbType="NVarChar(255)")]
	public string p_desc
	{
		get
		{
			return this._p_desc;
		}
		set
		{
			if ((this._p_desc != value))
			{
				this.Onp_descChanging(value);
				this.SendPropertyChanging();
				this._p_desc = value;
				this.SendPropertyChanged("p_desc");
				this.Onp_descChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.package_using")]
public partial class package_using : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _u_id;
	
	private System.Nullable<int> _u_cell;
	
	private string _u_reason;
	
	private string _u_batch;
	
	private System.Nullable<int> _u_num;
	
	private string _u_pkg_category;
	
	private string _u_user;
	
	private System.Nullable<System.DateTime> _u_added;
	
	private string _u_modifyby;
	
	private System.Nullable<System.DateTime> _u_modified;
	
	private System.Nullable<int> _u_status;
	
	private System.Nullable<int> _u_mailtimes;
	
	private EntityRef<cell_info> _cell_info;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onu_idChanging(int value);
    partial void Onu_idChanged();
    partial void Onu_cellChanging(System.Nullable<int> value);
    partial void Onu_cellChanged();
    partial void Onu_reasonChanging(string value);
    partial void Onu_reasonChanged();
    partial void Onu_batchChanging(string value);
    partial void Onu_batchChanged();
    partial void Onu_numChanging(System.Nullable<int> value);
    partial void Onu_numChanged();
    partial void Onu_pkg_categoryChanging(string value);
    partial void Onu_pkg_categoryChanged();
    partial void Onu_userChanging(string value);
    partial void Onu_userChanged();
    partial void Onu_addedChanging(System.Nullable<System.DateTime> value);
    partial void Onu_addedChanged();
    partial void Onu_modifybyChanging(string value);
    partial void Onu_modifybyChanged();
    partial void Onu_modifiedChanging(System.Nullable<System.DateTime> value);
    partial void Onu_modifiedChanged();
    partial void Onu_statusChanging(System.Nullable<int> value);
    partial void Onu_statusChanged();
    partial void Onu_mailtimesChanging(System.Nullable<int> value);
    partial void Onu_mailtimesChanged();
    #endregion
	
	public package_using()
	{
		this._cell_info = default(EntityRef<cell_info>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int u_id
	{
		get
		{
			return this._u_id;
		}
		set
		{
			if ((this._u_id != value))
			{
				this.Onu_idChanging(value);
				this.SendPropertyChanging();
				this._u_id = value;
				this.SendPropertyChanged("u_id");
				this.Onu_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_cell", DbType="Int")]
	public System.Nullable<int> u_cell
	{
		get
		{
			return this._u_cell;
		}
		set
		{
			if ((this._u_cell != value))
			{
				if (this._cell_info.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onu_cellChanging(value);
				this.SendPropertyChanging();
				this._u_cell = value;
				this.SendPropertyChanged("u_cell");
				this.Onu_cellChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_reason", DbType="NVarChar(255)")]
	public string u_reason
	{
		get
		{
			return this._u_reason;
		}
		set
		{
			if ((this._u_reason != value))
			{
				this.Onu_reasonChanging(value);
				this.SendPropertyChanging();
				this._u_reason = value;
				this.SendPropertyChanged("u_reason");
				this.Onu_reasonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_batch", DbType="NVarChar(50)")]
	public string u_batch
	{
		get
		{
			return this._u_batch;
		}
		set
		{
			if ((this._u_batch != value))
			{
				this.Onu_batchChanging(value);
				this.SendPropertyChanging();
				this._u_batch = value;
				this.SendPropertyChanged("u_batch");
				this.Onu_batchChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_num", DbType="Int")]
	public System.Nullable<int> u_num
	{
		get
		{
			return this._u_num;
		}
		set
		{
			if ((this._u_num != value))
			{
				this.Onu_numChanging(value);
				this.SendPropertyChanging();
				this._u_num = value;
				this.SendPropertyChanged("u_num");
				this.Onu_numChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_pkg_category", DbType="NVarChar(255)")]
	public string u_pkg_category
	{
		get
		{
			return this._u_pkg_category;
		}
		set
		{
			if ((this._u_pkg_category != value))
			{
				this.Onu_pkg_categoryChanging(value);
				this.SendPropertyChanging();
				this._u_pkg_category = value;
				this.SendPropertyChanged("u_pkg_category");
				this.Onu_pkg_categoryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_user", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string u_user
	{
		get
		{
			return this._u_user;
		}
		set
		{
			if ((this._u_user != value))
			{
				this.Onu_userChanging(value);
				this.SendPropertyChanging();
				this._u_user = value;
				this.SendPropertyChanged("u_user");
				this.Onu_userChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_added", DbType="DateTime")]
	public System.Nullable<System.DateTime> u_added
	{
		get
		{
			return this._u_added;
		}
		set
		{
			if ((this._u_added != value))
			{
				this.Onu_addedChanging(value);
				this.SendPropertyChanging();
				this._u_added = value;
				this.SendPropertyChanged("u_added");
				this.Onu_addedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_modifyby", DbType="VarChar(50)")]
	public string u_modifyby
	{
		get
		{
			return this._u_modifyby;
		}
		set
		{
			if ((this._u_modifyby != value))
			{
				this.Onu_modifybyChanging(value);
				this.SendPropertyChanging();
				this._u_modifyby = value;
				this.SendPropertyChanged("u_modifyby");
				this.Onu_modifybyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_modified", DbType="DateTime")]
	public System.Nullable<System.DateTime> u_modified
	{
		get
		{
			return this._u_modified;
		}
		set
		{
			if ((this._u_modified != value))
			{
				this.Onu_modifiedChanging(value);
				this.SendPropertyChanging();
				this._u_modified = value;
				this.SendPropertyChanged("u_modified");
				this.Onu_modifiedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_status", DbType="Int")]
	public System.Nullable<int> u_status
	{
		get
		{
			return this._u_status;
		}
		set
		{
			if ((this._u_status != value))
			{
				this.Onu_statusChanging(value);
				this.SendPropertyChanging();
				this._u_status = value;
				this.SendPropertyChanged("u_status");
				this.Onu_statusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_mailtimes", DbType="Int")]
	public System.Nullable<int> u_mailtimes
	{
		get
		{
			return this._u_mailtimes;
		}
		set
		{
			if ((this._u_mailtimes != value))
			{
				this.Onu_mailtimesChanging(value);
				this.SendPropertyChanging();
				this._u_mailtimes = value;
				this.SendPropertyChanged("u_mailtimes");
				this.Onu_mailtimesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cell_info_package_using", Storage="_cell_info", ThisKey="u_cell", OtherKey="cell_id", IsForeignKey=true)]
	public cell_info cell_info
	{
		get
		{
			return this._cell_info.Entity;
		}
		set
		{
			cell_info previousValue = this._cell_info.Entity;
			if (((previousValue != value) 
						|| (this._cell_info.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._cell_info.Entity = null;
					previousValue.package_using.Remove(this);
				}
				this._cell_info.Entity = value;
				if ((value != null))
				{
					value.package_using.Add(this);
					this._u_cell = value.cell_id;
				}
				else
				{
					this._u_cell = default(Nullable<int>);
				}
				this.SendPropertyChanged("cell_info");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cell_info")]
public partial class cell_info : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _cell_id;
	
	private string _cell_name;
	
	private string _cell_supervisor;
	
	private string _cell_BU;
	
	private System.Nullable<int> _cell_WIP_limit;
	
	private System.Nullable<int> _cell_WIP_tolerance;
	
	private System.Nullable<double> _cell_CT;
	
	private string _cell_pkg_building;
	
	private EntitySet<package_using> _package_using;
	
	private EntitySet<package_user> _package_user;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncell_idChanging(int value);
    partial void Oncell_idChanged();
    partial void Oncell_nameChanging(string value);
    partial void Oncell_nameChanged();
    partial void Oncell_supervisorChanging(string value);
    partial void Oncell_supervisorChanged();
    partial void Oncell_BUChanging(string value);
    partial void Oncell_BUChanged();
    partial void Oncell_WIP_limitChanging(System.Nullable<int> value);
    partial void Oncell_WIP_limitChanged();
    partial void Oncell_WIP_toleranceChanging(System.Nullable<int> value);
    partial void Oncell_WIP_toleranceChanged();
    partial void Oncell_CTChanging(System.Nullable<double> value);
    partial void Oncell_CTChanged();
    partial void Oncell_pkg_buildingChanging(string value);
    partial void Oncell_pkg_buildingChanged();
    #endregion
	
	public cell_info()
	{
		this._package_using = new EntitySet<package_using>(new Action<package_using>(this.attach_package_using), new Action<package_using>(this.detach_package_using));
		this._package_user = new EntitySet<package_user>(new Action<package_user>(this.attach_package_user), new Action<package_user>(this.detach_package_user));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int cell_id
	{
		get
		{
			return this._cell_id;
		}
		set
		{
			if ((this._cell_id != value))
			{
				this.Oncell_idChanging(value);
				this.SendPropertyChanging();
				this._cell_id = value;
				this.SendPropertyChanged("cell_id");
				this.Oncell_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell_name", DbType="VarChar(50)")]
	public string cell_name
	{
		get
		{
			return this._cell_name;
		}
		set
		{
			if ((this._cell_name != value))
			{
				this.Oncell_nameChanging(value);
				this.SendPropertyChanging();
				this._cell_name = value;
				this.SendPropertyChanged("cell_name");
				this.Oncell_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell_supervisor", DbType="VarChar(50)")]
	public string cell_supervisor
	{
		get
		{
			return this._cell_supervisor;
		}
		set
		{
			if ((this._cell_supervisor != value))
			{
				this.Oncell_supervisorChanging(value);
				this.SendPropertyChanging();
				this._cell_supervisor = value;
				this.SendPropertyChanged("cell_supervisor");
				this.Oncell_supervisorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell_BU", DbType="VarChar(50)")]
	public string cell_BU
	{
		get
		{
			return this._cell_BU;
		}
		set
		{
			if ((this._cell_BU != value))
			{
				this.Oncell_BUChanging(value);
				this.SendPropertyChanging();
				this._cell_BU = value;
				this.SendPropertyChanged("cell_BU");
				this.Oncell_BUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell_WIP_limit", DbType="Int")]
	public System.Nullable<int> cell_WIP_limit
	{
		get
		{
			return this._cell_WIP_limit;
		}
		set
		{
			if ((this._cell_WIP_limit != value))
			{
				this.Oncell_WIP_limitChanging(value);
				this.SendPropertyChanging();
				this._cell_WIP_limit = value;
				this.SendPropertyChanged("cell_WIP_limit");
				this.Oncell_WIP_limitChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell_WIP_tolerance", DbType="Int")]
	public System.Nullable<int> cell_WIP_tolerance
	{
		get
		{
			return this._cell_WIP_tolerance;
		}
		set
		{
			if ((this._cell_WIP_tolerance != value))
			{
				this.Oncell_WIP_toleranceChanging(value);
				this.SendPropertyChanging();
				this._cell_WIP_tolerance = value;
				this.SendPropertyChanged("cell_WIP_tolerance");
				this.Oncell_WIP_toleranceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell_CT", DbType="Float")]
	public System.Nullable<double> cell_CT
	{
		get
		{
			return this._cell_CT;
		}
		set
		{
			if ((this._cell_CT != value))
			{
				this.Oncell_CTChanging(value);
				this.SendPropertyChanging();
				this._cell_CT = value;
				this.SendPropertyChanged("cell_CT");
				this.Oncell_CTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell_pkg_building", DbType="VarChar(50)")]
	public string cell_pkg_building
	{
		get
		{
			return this._cell_pkg_building;
		}
		set
		{
			if ((this._cell_pkg_building != value))
			{
				this.Oncell_pkg_buildingChanging(value);
				this.SendPropertyChanging();
				this._cell_pkg_building = value;
				this.SendPropertyChanged("cell_pkg_building");
				this.Oncell_pkg_buildingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cell_info_package_using", Storage="_package_using", ThisKey="cell_id", OtherKey="u_cell")]
	public EntitySet<package_using> package_using
	{
		get
		{
			return this._package_using;
		}
		set
		{
			this._package_using.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cell_info_package_user", Storage="_package_user", ThisKey="cell_id", OtherKey="p_cell")]
	public EntitySet<package_user> package_user
	{
		get
		{
			return this._package_user;
		}
		set
		{
			this._package_user.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_package_using(package_using entity)
	{
		this.SendPropertyChanging();
		entity.cell_info = this;
	}
	
	private void detach_package_using(package_using entity)
	{
		this.SendPropertyChanging();
		entity.cell_info = null;
	}
	
	private void attach_package_user(package_user entity)
	{
		this.SendPropertyChanging();
		entity.cell_info = this;
	}
	
	private void detach_package_user(package_user entity)
	{
		this.SendPropertyChanging();
		entity.cell_info = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.package_user")]
public partial class package_user : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _p_user;
	
	private string _p_role;
	
	private System.Nullable<int> _p_cell;
	
	private EntityRef<cell_info> _cell_info;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onp_userChanging(string value);
    partial void Onp_userChanged();
    partial void Onp_roleChanging(string value);
    partial void Onp_roleChanged();
    partial void Onp_cellChanging(System.Nullable<int> value);
    partial void Onp_cellChanged();
    #endregion
	
	public package_user()
	{
		this._cell_info = default(EntityRef<cell_info>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_user", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string p_user
	{
		get
		{
			return this._p_user;
		}
		set
		{
			if ((this._p_user != value))
			{
				this.Onp_userChanging(value);
				this.SendPropertyChanging();
				this._p_user = value;
				this.SendPropertyChanged("p_user");
				this.Onp_userChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_role", DbType="VarChar(50)")]
	public string p_role
	{
		get
		{
			return this._p_role;
		}
		set
		{
			if ((this._p_role != value))
			{
				this.Onp_roleChanging(value);
				this.SendPropertyChanging();
				this._p_role = value;
				this.SendPropertyChanged("p_role");
				this.Onp_roleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_cell", DbType="Int")]
	public System.Nullable<int> p_cell
	{
		get
		{
			return this._p_cell;
		}
		set
		{
			if ((this._p_cell != value))
			{
				if (this._cell_info.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onp_cellChanging(value);
				this.SendPropertyChanging();
				this._p_cell = value;
				this.SendPropertyChanged("p_cell");
				this.Onp_cellChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cell_info_package_user", Storage="_cell_info", ThisKey="p_cell", OtherKey="cell_id", IsForeignKey=true)]
	public cell_info cell_info
	{
		get
		{
			return this._cell_info.Entity;
		}
		set
		{
			cell_info previousValue = this._cell_info.Entity;
			if (((previousValue != value) 
						|| (this._cell_info.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._cell_info.Entity = null;
					previousValue.package_user.Remove(this);
				}
				this._cell_info.Entity = value;
				if ((value != null))
				{
					value.package_user.Add(this);
					this._p_cell = value.cell_id;
				}
				else
				{
					this._p_cell = default(Nullable<int>);
				}
				this.SendPropertyChanged("cell_info");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
