#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3649
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[System.Data.Linq.Mapping.DatabaseAttribute(Name="batch")]
public partial class roleDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public roleDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["batchConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public roleDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public roleDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public roleDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public roleDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<mgr_user_role> mgr_user_role
	{
		get
		{
			return this.GetTable<mgr_user_role>();
		}
	}
}

[Table(Name="dbo.mgr_user_role")]
public partial class mgr_user_role
{
	
	private string _userid;
	
	private string _role;
	
	private string _location;
	
	public mgr_user_role()
	{
	}
	
	[Column(Storage="_userid", DbType="VarChar(50)")]
	public string userid
	{
		get
		{
			return this._userid;
		}
		set
		{
			if ((this._userid != value))
			{
				this._userid = value;
			}
		}
	}
	
	[Column(Storage="_role", DbType="VarChar(50)")]
	public string role
	{
		get
		{
			return this._role;
		}
		set
		{
			if ((this._role != value))
			{
				this._role = value;
			}
		}
	}
	
	[Column(Storage="_location", DbType="Nvarchar(50)")]
	public string location
	{
		get
		{
			return this._location;
		}
		set
		{
			if ((this._location != value))
			{
				this._location = value;
			}
		}
	}
}
#pragma warning restore 1591
